# Site settings
title:          Blog
description:    "Blog for personal projects and activities"
baseurl:        "/blog"
url:            "https://paritosh97.github.io"

# Author
author:
  name:         Paritosh Sharma
  url:          https://paritosh97.github.io
  email:        contact@paritosh-sharma.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
